#!/usr/bin/env python3
"""Regenerates requirements.txt with per-artifact sha256 hashes from PyPI.

Run only as part of a reviewed dependency update (docs/CONFORMANCE-SUITE.md):
bump a pin below, run this script, review the diff, and record the provenance
note beside the pin change.
"""

import json
import os
import urllib.request

PINS = [
    ("cryptography", "50.0.1"),
    ("cffi", "2.1.1"),
    ("pycparser", "3.0"),
    ("asn1crypto", "1.5.1"),
    ("jsonschema", "4.26.0"),
    ("attrs", "26.1.0"),
    ("jsonschema-specifications", "2025.9.1"),
    ("referencing", "0.37.0"),
    ("rpds-py", "2026.6.3"),
    ("typing-extensions", "4.16.0"),
]

HEADER = """# Pinned dependencies of the Python conformance verifier (PRUVZ-97).
# Generated by gen-requirements.py; provenance, review notes and the update
# policy live in docs/CONFORMANCE-SUITE.md. Hashes cover every artifact PyPI
# publishes for the pinned version, so
# `pip install --require-hashes -r requirements.txt` verifies on any platform.
"""


def main() -> None:
    lines = [HEADER]
    for name, version in PINS:
        with urllib.request.urlopen(f"https://pypi.org/pypi/{name}/{version}/json") as response:
            data = json.load(response)
        hashes = sorted({entry["digests"]["sha256"] for entry in data["urls"]})
        continuation = " \\\n".join(
            [f"{name}=={version}"] + [f"    --hash=sha256:{digest}" for digest in hashes]
        )
        lines.append(continuation)
    target = os.path.join(os.path.dirname(os.path.abspath(__file__)), "requirements.txt")
    with open(target, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines) + "\n")
    print(f"wrote {target}")


if __name__ == "__main__":
    main()
